name: "Edit Hackathon"
description: "Template for editing an existing hackathon in the repo."
title: "Edit Hackathon: [Hackathon Name]"
labels: "edit"
assignees: []
body:
  - type: dropdown
    id: applications
    attributes:
      label: "Applications"
        - label: "Is this hackathon still (going to be) accepting applications?"
          multiple:
          options:
          - "Yes"
          - "No"
  - type: dropdown
    id: status
    attributes:
      label: "Status"
        - label: "Is this hackathon still happening?"
          multiple:
          options:
          - "Yes"
          - "No"
          
  - type: input
    id: updated_hackathon_name
    attributes:
      label: "Updated Hackathon Name"
      description: "New name if applicable"
      placeholder: "Updated Hackathon Name"

  - type: input
    id: updated_date
    attributes:
      label: "Updated Date"
      description: "New date if applicable"
      placeholder: "YYYY-MM-DD"

  - type: input
    id: updated_location
    attributes:
      label: "Updated Location"
      description: "New location if applicable"
      placeholder: "Updated Location"

  - type: input
    id: updated_application_link
    attributes:
      label: "Updated Application/Link"
      description: "New link if applicable"
      placeholder: "https://example.com"

  - type: textarea
    id: reason_for_change
    attributes:
      label: "Reason for Change"
      description: "Briefly explain why the changes are necessary"
    validations:
      required: true

  - type: textarea
    id: additional_notes
    attributes:
      label: "Additional Notes"
      description: "Any additional notes or comments"
